# Generated by Django 5.0.2 on 2024-08-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_fotografo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
            ],
        ),
    ]
