# Generated by Django 5.0.2 on 2024-09-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_fotografo', '0003_albuns'),
    ]

    operations = [
        migrations.AddField(
            model_name='albuns',
            name='imagem',
            field=models.ImageField(default=2, upload_to='imagem_album'),
            preserve_default=False,
        ),
    ]
